import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { FeedbackDialog } from "@/components/FeedbackDialog";
import { Button } from "@/components/ui/button";
import { ButtonRow } from "@/components/ui/button-row";
import { StepDots } from "@/components/ui/step-dots";
import shotsJson from "@/assets/help/shots.json";
import { useT, type Localized } from "@/lib/i18n";
import { PROXY_URL } from "@/lib/llm/client";
import { useSettings } from "@/lib/settings";
import { cn } from "@/lib/utils";

/**
 * One thing per slide, in the order a first inquiry goes. Screenshots and the rings that point
 * at the control on each one are generated by `pnpm shots` (scripts/help-shots.ts); the ids here
 * must match the shot ids there. See docs/help-screenshots.md.
 */
const slides: { id: string; title: Localized; body: Localized }[] = [
  { id: "course", title: { ja: "🧭 コースを選ぶ", en: "🧭 Pick a course" }, body: { ja: "似た意味の語のグループから選びます。", en: "Choose a group of words with similar meanings." } },
  { id: "words", title: { ja: "🔤 比べる語を選ぶ", en: "🔤 Pick words to compare" }, body: { ja: "2語ずつ比べるのが見やすいです。", en: "Two at a time is easiest to see." } },
  { id: "genre", title: { ja: "🎬 場面を選ぶ", en: "🎬 Pick a scene" }, body: { ja: "例文のジャンルを決めます。", en: "Choose the kind of example sentences." } },
  { id: "examples", title: { ja: "👀 例文を眺める", en: "👀 Read the examples" }, body: { ja: "解説はありません。\n違いを自分で探します。", en: "There are no explanations.\nFind the differences yourself." } },
  { id: "observe", title: { ja: "🔍 観察する", en: "🔍 Observe" }, body: { ja: "気になった所を選んで印を付けます。", en: "Select what catches your eye and add it." } },
  { id: "hypothesis", title: { ja: "✍️ 仮説を書く", en: "✍️ Write a hypothesis" }, body: { ja: "「こういう時に使う」と自分の言葉で書きます。", en: "Say when each word is used, in your own words." } },
  { id: "translate", title: { ja: "🧪 翻訳テストで確かめる", en: "🧪 Test with a translation" }, body: { ja: "どの語が使われるか予想してから答えを見ます。", en: "Predict which word appears, then check." } },
  { id: "save", title: { ja: "📒 まとめて保存する", en: "📒 Sum up and save" }, body: { ja: "気づきノートでいつでも読み返せます。", en: "Read it again any time in your notes." } },
  { id: "next", title: { ja: "🔁 次の一手を選ぶ", en: "🔁 Pick the next step" }, body: { ja: "順番は自由です。\n何度でも回します。", en: "Any order is fine.\nGo around as many times as you like." } },
];

/** Where to draw the ring, in % of the screenshot. */
interface Shot {
  width: number;
  height: number;
  rings: { x: number; y: number; w: number; h: number }[];
}
const shots = shotsJson as Record<string, Record<string, Shot>>;
const images = import.meta.glob<string>("../assets/help/*/*.webp", { eager: true, query: "?url", import: "default" });

/** The screenshot for the screen language, falling back to the Japanese one. */
function shotFor(lang: string, id: string) {
  for (const l of [lang, "ja"]) {
    const src = images[`../assets/help/${l}/${id}.webp`];
    if (src && shots[l]?.[id]) return { src, ...shots[l][id] };
  }
  return null;
}

function Screenshot({ id, alt }: { id: string; alt: string }) {
  const { uiLang } = useSettings();
  const shot = shotFor(uiLang, id);
  if (!shot) return <div className="mt-4 grid h-80 w-56 place-items-center rounded-2xl border border-dashed text-sm text-muted-foreground">{alt}</div>;
  const ratio = shot.height / shot.width;
  // Height is whichever runs out first: the screen height (leaving room for the text and buttons),
  // the screen width, or a phone-like 22rem width on large screens. The width follows the ratio,
  // so the rings (in %) always sit on the same spot of the picture.
  const style: CSSProperties = { aspectRatio: `${shot.width} / ${shot.height}`, height: `min(calc(100dvh - 17rem), calc((100vw - 2rem) * ${ratio}), calc(22rem * ${ratio}))` };
  return (
    <div className="relative mt-4 overflow-hidden rounded-2xl border shadow-md" style={style}>
      <img src={shot.src} alt={alt} draggable={false} className="absolute inset-0 size-full select-none" />
      {shot.rings.map((r, i) => (
        <span
          key={i}
          aria-hidden
          className="pointer-events-none absolute animate-pulse rounded-xl border-[3px] border-blue-600 shadow-[0_0_0_4px_rgb(37_99_235/0.25)]"
          style={{ left: `${r.x}%`, top: `${r.y}%`, width: `${r.w}%`, height: `${r.h}%` }}
        />
      ))}
    </div>
  );
}

export function HelpPage() {
  const t = useT();
  const { uiLang } = useSettings();
  const [params, setParams] = useSearchParams();
  const index = Math.min(Math.max((Number(params.get("s")) || 1) - 1, 0), slides.length - 1);
  const slide = slides[index];
  const last = index === slides.length - 1;
  const [dir, setDir] = useState<1 | -1>(1);
  const [feedback, setFeedback] = useState(false);
  const swipe = useRef<{ x: number; y: number } | null>(null);

  const go = useCallback(
    (next: number) => {
      if (next < 0 || next >= slides.length) return;
      setDir(next > index ? 1 : -1);
      setParams({ s: String(next + 1) }, { replace: true });
    },
    [index, setParams],
  );

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") go(index + 1);
      else if (e.key === "ArrowLeft") go(index - 1);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [go, index]);

  // Fetch the neighbours ahead of time so a swipe never shows an empty frame.
  useEffect(() => {
    for (const i of [index - 1, index + 1]) {
      const src = slides[i] && shotFor(uiLang, slides[i].id)?.src;
      if (src) new Image().src = src;
    }
  }, [index, uiLang]);

  return (
    <div className="mx-auto flex max-w-md flex-col items-center px-4 py-6">
      <StepDots total={slides.length} current={index} />
      <div
        key={slide.id}
        className={cn("flex flex-col items-center pt-4 animate-in fade-in duration-300", dir > 0 ? "slide-in-from-right-4" : "slide-in-from-left-4")}
        style={{ touchAction: "pan-y" }}
        onPointerDown={(e) => (swipe.current = { x: e.clientX, y: e.clientY })}
        onPointerUp={(e) => {
          const start = swipe.current;
          swipe.current = null;
          if (!start) return;
          const dx = e.clientX - start.x;
          if (Math.abs(dx) > 40 && Math.abs(dx) > Math.abs(e.clientY - start.y)) go(dx < 0 ? index + 1 : index - 1);
        }}
      >
        <h1 className="text-center text-xl font-semibold">{t(slide.title)}</h1>
        <p className="mt-1 min-h-10 text-center text-sm whitespace-pre-line text-muted-foreground">{t(slide.body)}</p>
        <Screenshot id={slide.id} alt={t(slide.title)} />
      </div>
      <ButtonRow className="justify-center pt-6">
        <Button variant="outline" disabled={index === 0} onClick={() => go(index - 1)}>{t({ ja: "◀ 戻る", en: "◀ Back" })}</Button>
        {last ? (
          <Button render={<Link to="/" />} nativeButton={false}>{t({ ja: "🚀 さっそく始める", en: "🚀 Get started" })}</Button>
        ) : (
          <Button onClick={() => go(index + 1)}>{t({ ja: "進む ▶", en: "Next ▶" })}</Button>
        )}
      </ButtonRow>
      {/* The end of the help is where someone who is still lost gives up, so offer the way to ask here too. */}
      {last && PROXY_URL && (
        <p className="pt-8 text-center text-sm whitespace-pre-line text-muted-foreground">
          {t({ ja: "分かりにくい所や、うまく動かない所はありませんでしたか？", en: "Anything unclear, or not working as it should?" })}
          <br />
          <Button variant="link" className="h-auto px-0 py-1" onClick={() => setFeedback(true)}>{t({ ja: "✉️ ご意見・不具合を伝える", en: "✉️ Tell us about it" })}</Button>
        </p>
      )}
      <FeedbackDialog open={feedback} onOpenChange={setFeedback} />
    </div>
  );
}
